version: "3.7"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:5.4.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - broker
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: Argentum4!
      KM_ARGS: -Djava.net.preferIPv4Stack=true
      
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Argentum4!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    
  auth:
    image: auth
    build:
      context: src/
      dockerfile: UberPopug.AuthService/Dockerfile    
    depends_on:
      - database   
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  tracker:
    image: tracker
    build:
      context: src/
      dockerfile: UberPopug.TaskTrackerService/Dockerfile    
    depends_on:
      - database   
    ports:
      - "5010:5010"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  accounting:
    image: accounting
    build:
      context: src/
      dockerfile: UberPopug.AccountingService/Dockerfile    
    depends_on:
      - database   
    ports:
      - "5020:5020"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development